export class Cadastro {
  ecc? : string;
  nome_padrinho? : string;
  esposa_nome? : string;
  esposa_nome_completo?: string; 
  esposa_dt_nasc?: string; 
  esposa_profissao?: string; 
  esposa_email?: string; 
  esposa_celular?: string; 
  esposa_identidade?: string;
   esposa_orgao?: string;
    esposa_cpf?: string;
    esposa_saude?: string;
    esposa_medicamento?: string;
    esposa_problema_saude?: string; 
    esposa_religiao?: string; 
    esposo_nome?: string; 
    esposo_nome_completo?: string; 
  esposo_dt_nasc?: string; 
  esposo_profissao?: string; 
  esposo_email?: string; 
  esposo_celular?: string; 
  esposo_identidade?: string; 
  esposo_orgao?: string; 
  esposo_cpf?: string; 
  esposo_saude?: string; 
  esposo_medicamento?: string;
  esposo_diabetico?: string;
  esposo_vegetariano?: string;
  esposo_problema_saude?: string;
  esposo_religiao?: string;
  endereco?: string; 
  bairro?: string;
  cep?: string; 
  cidade?: string;
  tel_residencial?: string;
  dt_casamento?: string;
  responsavel?: string; 
  padrinho?: string;
  casal?: string; 
  ativo?: string; 
  separado?: string;
  guara?: string; 
  esposo_falecido?: string;
   esposa_falecida?: string;

}
